<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127183353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competiciones.ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuario_id INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_941B54BDB38439E ON competiciones.ranking (usuario_id)');
        $this->addSql('CREATE INDEX IDX_941B54B12469DE2 ON competiciones.ranking (category_id)');
        $this->addSql('CREATE TABLE competiciones.ranking_competicion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, competicion_id INT DEFAULT NULL, ranking_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_948FEA93D9407152 ON competiciones.ranking_competicion (competicion_id)');
        $this->addSql('CREATE INDEX IDX_948FEA9320F64684 ON competiciones.ranking_competicion (ranking_id)');
        $this->addSql('CREATE TABLE competiciones.review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT NOT NULL, stars INT NOT NULL, usuario_id INT DEFAULT NULL, competicion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53E4FA5FDB38439E ON competiciones.review (usuario_id)');
        $this->addSql('CREATE INDEX IDX_53E4FA5FD9407152 ON competiciones.review (competicion_id)');
        $this->addSql('ALTER TABLE competiciones.ranking ADD CONSTRAINT FK_941B54BDB38439E FOREIGN KEY (usuario_id) REFERENCES competiciones.usuario (id)');
        $this->addSql('ALTER TABLE competiciones.ranking ADD CONSTRAINT FK_941B54B12469DE2 FOREIGN KEY (category_id) REFERENCES competiciones.category (id)');
        $this->addSql('ALTER TABLE competiciones.ranking_competicion ADD CONSTRAINT FK_948FEA93D9407152 FOREIGN KEY (competicion_id) REFERENCES competiciones.competicion (id)');
        $this->addSql('ALTER TABLE competiciones.ranking_competicion ADD CONSTRAINT FK_948FEA9320F64684 FOREIGN KEY (ranking_id) REFERENCES competiciones.ranking (id)');
        $this->addSql('ALTER TABLE competiciones.review ADD CONSTRAINT FK_53E4FA5FDB38439E FOREIGN KEY (usuario_id) REFERENCES competiciones.usuario (id)');
        $this->addSql('ALTER TABLE competiciones.review ADD CONSTRAINT FK_53E4FA5FD9407152 FOREIGN KEY (competicion_id) REFERENCES competiciones.competicion (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competiciones.ranking DROP CONSTRAINT FK_941B54BDB38439E');
        $this->addSql('ALTER TABLE competiciones.ranking DROP CONSTRAINT FK_941B54B12469DE2');
        $this->addSql('ALTER TABLE competiciones.ranking_competicion DROP CONSTRAINT FK_948FEA93D9407152');
        $this->addSql('ALTER TABLE competiciones.ranking_competicion DROP CONSTRAINT FK_948FEA9320F64684');
        $this->addSql('ALTER TABLE competiciones.review DROP CONSTRAINT FK_53E4FA5FDB38439E');
        $this->addSql('ALTER TABLE competiciones.review DROP CONSTRAINT FK_53E4FA5FD9407152');
        $this->addSql('DROP TABLE competiciones.ranking');
        $this->addSql('DROP TABLE competiciones.ranking_competicion');
        $this->addSql('DROP TABLE competiciones.review');
    }
}
