<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127182536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competiciones.category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, image TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE category_competicion (category_id INT NOT NULL, competicion_id INT NOT NULL, PRIMARY KEY (category_id, competicion_id))');
        $this->addSql('CREATE INDEX IDX_CF5F01FC12469DE2 ON category_competicion (category_id)');
        $this->addSql('CREATE INDEX IDX_CF5F01FCD9407152 ON category_competicion (competicion_id)');
        $this->addSql('CREATE TABLE competiciones.usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, mail VARCHAR(500) NOT NULL, rol INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON competiciones.usuario (username)');
        $this->addSql('ALTER TABLE category_competicion ADD CONSTRAINT FK_CF5F01FC12469DE2 FOREIGN KEY (category_id) REFERENCES competiciones.category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_competicion ADD CONSTRAINT FK_CF5F01FCD9407152 FOREIGN KEY (competicion_id) REFERENCES competiciones.competicion (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category_competicion DROP CONSTRAINT FK_CF5F01FC12469DE2');
        $this->addSql('ALTER TABLE category_competicion DROP CONSTRAINT FK_CF5F01FCD9407152');
        $this->addSql('DROP TABLE competiciones.category');
        $this->addSql('DROP TABLE category_competicion');
        $this->addSql('DROP TABLE competiciones.usuario');
    }
}
